title: Michelle Michel
description: Une super chorale Ã  Rennes. Pour nous, pour vous.
remote_theme: ColinMaudry/cayman
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
  show_downloads: false
matomo_id: 15
